### PR TITLE
Remove boost dependency in gazer-theta, support finding theta by environment variables

### LINKED ISSUE #31: Use environment variables for configuration-related options
It is hard to set up a development environment for Gazer and Theta. Of course, one must do it only once, but it would be nice to improve this :)

The problem I've come across is: When running `make check-functional`, there is no way of passing where are the libraries and jar file. If, as it is for `$GAZER_TOOLS_DIR`, an environment variable was used, one would easily be able to use `make check-functional` and `tools/gazer-theta` without a bloated parameter list.

Developing theta and gazer side-by-side is a pain (as one *must* use that `--theta-path` parameter, which is impossible sometimes).

Create environment variables that are passed to Theta, instead of passing them as arguments.
This removes coupling to the certain versions of Theta (which might become a problem), and also helps configuring a workspace for developing Theta and Gazer.

This is related to only configuration, e.g. where libz3 resides or where to find the jar file.

Also, I'm okay with an _let's do both_ way, that configuration passed as environment variables are overriden by the parameters. (Setting both `--theta-path` and (e.g.) `THETA_JAR` envvar the `--theta-path` takes precedence).

### PR DESCRIPTION
**Pull request by sallaigy**
Fixes #31

### CODE REVIEW

**Review by rl555 — COMMENTED** [review]
I would and not remove boost dependency, as it would be useful to run on Windows target.
This change would break some configurations, and it does not sound too good...

Before now, I did not know it's not trivial to [get binary path](https://stackoverflow.com/questions/28745252/getting-directory-of-binary-in-c)...

I think using boost to improve compatibility is a better.

My proposal would be to only support envvars for now, and a more robust locateTheta implementation would be useful for later.

As robust solution, I mean removing Linux-specific working (`readlink /proc/self/exe`, which may not be handled well by mingw or cygwin), instead:
1) try args[0] as relative/absolute path from current directory. If missed, then it should be in PATH envvar.
2) iterate through PATH, delimiter is `const char llvm::sys::EnvPathSeparator`, try to find it from there.

Probably that is what the POSIX says about how to find a binary, so it would be something POSIX-compliant.

**Comment by sallaigy** [comment]
I am not a fan of this dependency, and I actually want to see it gone. Linking with the whole boost filesystem library just for the sake of finding the binary is an overkill to me and has bugged me for a while. Note that `/proc/self/exe` _should_ be okay on Linux, as the Boost implementation also uses this method.

In any case, I will add the heuristic based on argv[0], just note that it will not be entirely reliable either.

**Comment by radl97** [comment]
Note that I've seen a boost:indirect_iterator in CFA's locals() and globals(). But no linkage is needed, because it is header-only there.

(I'm @rl555 :D )

**Comment by sallaigy** [comment]
@rl555 @radl97 (Do you have other usernames?) As of now, `ExprRef` is also just a wrapper to `boost::intrusive_ptr` and we use Boost here and there in other places, but all those dependencies are header-only.

**Review by rl555 — APPROVED** [review]
LGTM

( @rl555 is a username I want to get rid of, sorry for the confusion :no_mouth: )

**Pull request merged**
